#!/usr/bin/python
# import the python renderman library
import prman

def oneElem(x,y,z):
    ri.TransformBegin()
    ri.Rotate(90, x,y,z)
    ri.Cylinder(0.1,-2,2,360) 
    ri.TransformBegin()
    ri.Translate(0,0,-2)
    ri.Sphere (0.3,-1, 1, 360)
    ri.TransformEnd()
    ri.TransformBegin()
    ri.Translate(0,0,2)
    ri.Sphere (0.3,-1, 1, 360)
    ri.TransformEnd()
    ri.TransformEnd()

def tripod(x,z):
    ri.TransformBegin()
    ri.Rotate(10,0,1,0)
    ri.Translate(x,0,z)
    ri.TransformBegin()
    ri.Translate(0,1.5,0)
    ri.Rotate(40,1,0,0)
    ri.Rotate(45,0,0,1)
    oneElem(1,0,0)
    oneElem(0,0,1)
    oneElem(0,1,0)
    ri.TransformEnd()
    ri.TransformEnd()

def Cube(width=1.0,height=1.0,depth=1.0) :	
	w=width/2.0
	h=height/2.0
	d=depth/2.0
	ri.ArchiveRecord(ri.COMMENT, 'Cube Generated by Cube Function')
	#rear
	face=[-w,-h,d,-w,h,d,w,-h,d,w,h,d]								
	ri.Patch("bilinear",{'P':face})
	#front
	face=[-w,-h,-d,-w,h,-d,w,-h,-d,w,h,-d]								
	ri.Patch("bilinear",{'P':face})
	#left
	face=[-w,-h,-d,-w,h,-d,-w,-h,d,-w,h,d]									
	ri.Patch("bilinear",{'P':face})
	#right
	face=[w,-h,-d,w,h,-d,w,-h,d,w,h,d]								
	ri.Patch("bilinear",{'P':face})
	#bottom
	face=[w,-h,d,w,-h,-d,-w,-h,d,-w,-h,-d]								
	ri.Patch("bilinear",{'P':face})
	#top
	face=[w,h,d,w,h,-d,-w,h,d,-w,h,-d]								
	ri.Patch("bilinear",{'P':face})
	ri.ArchiveRecord(ri.COMMENT, '--End of Cube Function--')

ri = prman.Ri() # create an instance of the RenderMan interface
ri.Option('rib', {'string asciistyle': 'indented'})

filename = 'Scene.rib'
# this is the begining of the rib archive generation we can only
# make RI calls after this function else we get a core dump
ri.Begin('__render')

# now we add the display element using the usual elements
# FILENAME DISPLAY Type Output format
ri.Display('Scene.exr', 'it', 'rgba')

ri.Format(1920,1080,1)
# now set the projection to perspective
ri.Projection(ri.PERSPECTIVE,{ri.FOV:50}) 

# now we start our world
ri.WorldBegin()

ri.Translate(0,-2,10)
#ri.Rotate(-20,1,0,0)

ri.TransformBegin()
ri.Rotate(-90,1,0,0)
ri.Scale(7,7,7)
ri.Translate(0, 0, -1)
face=[-1,-1,1, -1,1,1, 1,-1,1, 1,1,1]								
ri.Patch("bilinear",{'P':face})
ri.TransformEnd()

ri.TransformBegin()
ri.Translate(-4,0,0)
ri.Rotate(-90,1,0,0)
ri.Rotate(20,0,0,1)
ri.AttributeBegin()
ri.Bxdf( 'PxrDiffuse','diffuse', 
{
'color diffuseColor' : [ 0.7, 0.1, 0]
})
ri.Geometry("teapot")
ri.AttributeEnd()
ri.TransformEnd()

ri.TransformBegin()
ri.AttributeBegin()
ri.Bxdf( 'PxrDiffuse','diffuse', 
{
'color diffuseColor' : [ 0, 0.9, 0.1]
})
tripod(3,3)
tripod(1,-1)
tripod(4,-3)
ri.AttributeEnd()
ri.TransformEnd()

ri.TransformBegin() 
ri.Translate( 0,1,-3)
ri.Rotate( 25,0,1,0)
ri.AttributeBegin()
ri.Bxdf( 'PxrDiffuse','diffuse', 
{
'color diffuseColor' : [ 0, 0.1, 0.9]
})
Cube(2,2,2)
ri.AttributeEnd()
ri.TransformEnd()

ri.WorldEnd()
# and finally end the rib file
ri.End()